export function helpCommand(): void {
  console.log('Claude Code CLI 配置管理工具');
  console.log('');
  console.log('用法: cccli <command> [options]');
  console.log('');
  console.log('命令:');
  console.log('  set         <config_name> <key> <value>  设置配置项');
  console.log('              Key快捷: URL|TOKEN|KEY|MODEL|HAIKU|OPUS|SONNET|REASON|TEAMS');
  console.log('  active      <config_name> [--force]      激活指定配置');
  console.log('  list                                     列出所有配置');
  console.log('  get         <config_name>                查看配置详情');
  console.log('  test        <config_name>                测试配置连通性');
  console.log('  cc          <subcommand>                 Claude Code 管理');
  console.log('              install                      安装 Claude Code');
  console.log('              update                       更新 Claude Code');
  console.log('              upgrade                      升级 Claude Code');
  console.log('              version                      查看 Claude Code 版本');
  console.log('  skills      --list                       列出所有 skills');
  console.log('              -l 或 list                   系统级和项目级 skills');
  console.log('              --remove <name>              删除指定 skill');
  console.log('              -r <name>                    同上，同名多个时需选择');
  console.log('  env         [proxy]                      查看环境变量配置');
  console.log('  proxy       <proxy_name> <proxy_value>   设置代理环境变量');
  console.log('              --unset <proxy_name>         清除代理环境变量');
  console.log('  completion  <shell>                      生成 Shell 补全脚本');
  console.log('  q           <template> <auth_key> [model] 快速配置环境');
  console.log('              --list, -l                   列出可用模板');
  console.log('              --init                       初始化默认模板');
  console.log('              --init --force               强制覆盖现有配置');
  console.log('              (无参数)                     交互式配置模式');
  console.log('  export      [json]                     导出配置为JSON格式');
  console.log('  unset       <config_name> [--force]      删除指定配置');
  console.log('  upgrade                                  更新到最新版本');
  console.log('  update                                   同 upgrade');
  console.log('  help 或 ?                                显示帮助信息');
  console.log('');
  console.log('示例:');
  console.log('  cccli set kimi TOKEN sk-xxxxx');
  console.log('  cccli set kimi URL https://api.kimi.com/coding/');
  console.log('  cccli set kimi MODEL claude-3-opus-20240229');
  console.log('  cccli active kimi');
  console.log('  cccli active kimi --force');
  console.log('  cccli list');
  console.log('  cccli get kimi');
  console.log('  cccli test ali_coding');
  console.log('  cccli cc install');
  console.log('  cccli cc update');
  console.log('  cccli cc upgrade');
  console.log('  cccli cc version');
  console.log('  cccli skills --list');
  console.log('  cccli skills -l');
  console.log('  cccli skills -r google-trends');
  console.log('  cccli env');
  console.log('  cccli env proxy');
  console.log('  cccli proxy http_proxy http://127.0.0.1:18080');
  console.log('  cccli proxy --unset http_proxy');
  console.log('  cccli q kimi_coding sk-xxxxx');
  console.log('  cccli q ali_coding sk-xxxxx claude-3-opus-20240229');
  console.log('  cccli q mimo sk-xxxxx');
  console.log('  cccli q step_coding sk-xxxxx');
  console.log('  cccli q --list');
  console.log('  cccli q --init --force');
  console.log('  cccli export json');
  console.log('  cccli unset kimi');
  console.log('  cccli unset kimi --force');
  console.log('  cccli completion bash');
  console.log('  cccli ?');
  console.log('');
  console.log('跨平台支持: Windows, macOS, Linux');
  console.log('提示: 使用 "cccli completion --install" 查看 Shell 补全脚本安装方法');
}
