export function helpCommand(): void {
  console.log('Claude Code CLI 配置管理工具');
  console.log('');
  console.log('用法: cc <command> [options]');
  console.log('');
  console.log('命令:');
  console.log('  set         <config_name> <key> <value>  设置配置项');
  console.log('  active      <config_name> [--force]      激活指定配置');
  console.log('  list                                     列出所有配置');
  console.log('  get         <config_name>                查看配置详情');
  console.log('  env         [proxy]                      查看环境变量配置');
  console.log('  proxy       <proxy_name> <proxy_value>   设置代理环境变量');
  console.log('              --unset <proxy_name>         清除代理环境变量');
  console.log('  completion  <shell>                      生成 Shell 补全脚本');
  console.log('  q           <template> <auth_key>       快速配置环境');
  console.log('              --list                       列出可用模板');
  console.log('              --init                       初始化默认模板');
  console.log('  unset       <config_name> [--force]      删除指定配置');
  console.log('  upgrade                                  更新到最新版本');
  console.log('  help 或 ?                                显示帮助信息');
  console.log('');
  console.log('示例:');
  console.log('  cc set kimi ANTHROPIC_AUTH_TOKEN sk-xxxxx');
  console.log('  cc set kimi ANTHROPIC_BASE_URL https://api.kimi.com/coding/');
  console.log('  cc active kimi');
  console.log('  cc active kimi --force');
  console.log('  cc list');
  console.log('  cc get kimi');
  console.log('  cc env');
  console.log('  cc env proxy');
  console.log('  cc proxy http_proxy http://127.0.0.1:18080');
  console.log('  cc proxy --unset http_proxy');
  console.log('  cc q kimi_coding sk-xxxxx');
  console.log('  cc q --list');
  console.log('  cc unset kimi');
  console.log('  cc unset kimi --force');
  console.log('  cc completion bash');
  console.log('  cc ?');
  console.log('');
  console.log('跨平台支持: Windows, macOS, Linux');
  console.log('提示: 使用 "cc completion --install" 查看 Shell 补全脚本安装方法');
}
